# Generated by Django 4.1.6 on 2024-03-09 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('prn', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('cgpa', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
