# Generated by Django 4.1.6 on 2024-03-09 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_name_user_password_remove_user_number_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
