# Generated by Django 4.1.6 on 2024-03-10 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='email',
        ),
        
        migrations.AddField(
            model_name='users',
            name='prn',
            field=models.CharField(default='210021027643', max_length=25),
        ),
        migrations.AddField(
            model_name='users',
            name='type',
            field=models.CharField(default='student', max_length=10),
        ),
    ]
