# Generated by Django 4.1.6 on 2024-03-10 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_users_email_users_prn_users_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'ordering': ['prn', 'password', 'type']},
        ),
    ]
