# Generated by Django 4.1.6 on 2024-03-10 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_users_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='stud_id',
        ),
        migrations.AddField(
            model_name='notification',
            name='prn',
            field=models.CharField(default='210021027643', max_length=25),
        ),
    ]
